Normalize the ValidationMassages texts
ncats/gsrs-spring-module-substances pull request #349
Opened 2024-07-04 08:57 UTC by epuzanov

This PR Normalized the Validators Messages. The duplcated empty spaces and empty spaces at the end of the message will be removed. The Validation messages will be changed to support MessageId generation.

2024-07-04 15:38 UTC, ChemMitch requested changes
This is good work; I like cleaning up our messages.
One more thing: in BdNumModificationValidator, can you change 'Can not' to 'Cannot' which is standard?  (I know, English is a funny language...)

2024-07-09 13:42 UTC, blueSwordfish approved these changes

2024-07-09 13:42 UTC, blueSwordfish approved these changes

2024-07-09 13:45 UTC, blueSwordfish approved these changes

2024-07-09 13:45 UTC, merged